config/routes.rb
Rails.application.routes.draw do
  resources :personalities, only: [:index, :show, :create]
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "personalities#index"

  get '/signup', to: "users#new", as: "signup"
  post '/signup', to: "users#create"
  
  get '/login', to: "auth#login", as: "login"
  post '/login', to: "auth#authenticate"

  get '/logout', to: "auth#logout"

  get '/quiz_question_1', to:"answers_users#question1"
  post '/quiz_question_1', to:"answers_users#create_q1"

  get '/quiz_question_2', to:"answers_users#question2"
  post '/quiz_question_2', to:"answers_users#create_q2"

  get '/quiz_question_3', to:"answers_users#question3"
  post '/quiz_question_3', to:"answers_users#create_q3"

  get '/quiz_question_4', to:"answers_users#question4"
  post '/quiz_question_4', to:"answers_users#create_q4"

end

app/models/answer.rb
class Answer < ApplicationRecord
    has_many :answers_users
    has_many :users, through: :answers_users
end

app/models/answers_user.rb
class AnswersUser < ApplicationRecord
    belongs_to :user 
    belongs_to :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/personality.rb
class Personality < ApplicationRecord
    has_many :users
end

app/models/user.rb
class User < ApplicationRecord
    has_many :friends, dependent: :destroy
    has_many :answers, through: :answers_users
    has_many :answers_users
    belongs_to :personality, optional: true

    validates :name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :bio, presence: true

    def calculate_personality
        answer1 = AnswersUser.find_by(user_id: self.id, answer_id: 1).response
        answer2 = AnswersUser.find_by(user_id: self.id, answer_id: 2).response
        answer3 = AnswersUser.find_by(user_id: self.id, answer_id: 3).response
        answer4 = AnswersUser.find_by(user_id: self.id, answer_id: 4).response
        personality_string = answer1 + answer2 + answer3 + answer4 
        personality = Personality.find_by(name: personality_string)
        self.personality_id = personality.id
        personality
    end

    def personality 
        if self.personality_id
            return Personality.find_by(id: self.personality_id)
        else
            return "TBD"
        end
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/answers_users_controller.rb
class AnswersUsersController < ApplicationController
    def question1 
        @answer = Answer.all[0]
    end

    def create_q1
        @answer = Answer.all[0]
        @answers_user = AnswersUser.new(user_id: current_user.id, response: params["/quiz_question_1"]["response"], answer_id: @answer.id)
        if @answers_user.save 
            redirect_to quiz_question_2_path
        else
            render :question1
        end
    end

    def question2
        @answer = Answer.all[1]
    end

    def create_q2
        @answer = Answer.all[1]
        @answers_user = AnswersUser.new(user_id: current_user.id, response: params["/quiz_question_2"]["response"], answer_id: @answer.id)
        if @answers_user.save 
            redirect_to quiz_question_3_path
        else
            render :question2
        end
    end

    def question3
        @answer = Answer.all[2]
    end

    def create_q3
        @answer = Answer.all[2]
        @answers_user = AnswersUser.new(user_id: current_user.id, response: params["/quiz_question_3"]["response"], answer_id: @answer.id)
        if @answers_user.save 
            redirect_to quiz_question_4_path
        else
            render :question3
        end
    end

    def question4
        @answer = Answer.all[3]
    end

    def create_q4
        @answer = Answer.all[3]
        @answers_user = AnswersUser.new(user_id: current_user.id, response: params["/quiz_question_4"]["response"], answer_id: @answer.id)
        if @answers_user.save 
            redirect_to user_path(current_user)
        else
            render :question4
        end
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :require_login, :current_user

    def current_user
        User.find_by(id: session[:user_id])
    end

    def require_login
        if !logged_in?
            redirect_to login_path
        end
    end

    def logged_in?
        !!session[:user_id]
    end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController 
    helper_method :logout
    def login
    end

    def authenticate
        @user = User.find_by(username: params[:auth][:username])
        if @user 
            session[:user_id] = @user.id
            redirect_to personalities_path
        else
            flash[:message] = "Incorrect Information"
            render :login
        end
    end

    def logout
        session.clear
        cookies.clear
        redirect_to login_path
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
end

app/controllers/personalities_controller.rb
class PersonalitiesController < ApplicationController
    before_action :require_login

    def index 
        @personalities = Personality.all
    end

    def show 
        @personality = Personality.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    before_action :require_login
    skip_before_action :require_login, only: [:new, :create]
    
    def index 
        @users = User.all
    end

    def new 
        @user = User.new
    end

    def create 
        @user = User.new(username: params[:user][:username], name: params[:user][:name], bio: params[:user][:bio])
        if @user.save
            params[:user][:friend_ids].each do |friend_id| 
                if friend_id != ""
                    Friend.create(user_id: @user.id, friend_id: friend_id)
                end
            end
            redirect_to login_path
        else 
            flash[:message] = @user.errors.full_messages
            render :new
        end
    end

    def update 
        if @user.update(user_params)
            redirect_to @user
        else 
            render :edit
        end
    end

    def destroy 
        Friend.where(friend_id: @user.id).destroy_all
        @user.destroy

        redirect_to logout_path
    end

    private

    def find_user 
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :name, :bio, friend_ids: [])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/answers_users_helper.rb
module AnswersUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/personalities_helper.rb
module PersonalitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers_users/question1.html.erb
<h1>Personality Quiz</h1>
<p>Select the item that you identify with most:</p>
<%= form_for quiz_question_1_path do |f| %>
    1. <%= f.label @answer[:question] %>
    <p></p>
    <%= f.radio_button :response, "I" , :checked => true %>
    <%= f.label :option1, @answer[:option1] %>
    <p></p>
    <%= f.radio_button :response, "E" %>
    <%= f.label :option2, @answer[:option2] %>
    <p></p>
    <%= f.submit "Next Question" %>
<% end %>

app/views/answers_users/question2.html.erb
<h1>Personality Quiz</h1>
<p>Select the item that you identify with most:</p>
<%= form_for quiz_question_2_path do |f| %>
    2. <%= f.label @answer[:question] %>
    <p></p>
    <%= f.radio_button :response, "S" , :checked => true %>
    <%= f.label :option1, @answer[:option1] %>
    <p></p>
    <%= f.radio_button :response, "N" %>
    <%= f.label :option2, @answer[:option2] %>
    <p></p>
    <%= f.submit "Next Question" %>
<% end %>

app/views/answers_users/question3.html.erb
<h1>Personality Quiz</h1>
<p>Select the item that you identify with most:</p>
<%= form_for quiz_question_3_path do |f| %>
    3. <%= f.label @answer[:question] %>
    <p></p>
    <%= f.radio_button :response, "T" , :checked => true %>
    <%= f.label :option1, @answer[:option1] %>
    <p></p>
    <%= f.radio_button :response, "F" %>
    <%= f.label :option2, @answer[:option2] %>
    <p></p>
    <%= f.submit "Next Question" %>
<% end %>

app/views/answers_users/question4.html.erb
<h1>Personality Quiz</h1>
<p>Select the item that you identify with most:</p>
<%= form_for quiz_question_4_path do |f| %>
    4. <%= f.label @answer[:question] %>
    <p></p>
    <%= f.radio_button :response, "J" , :checked => true %>
    <%= f.label :option1, @answer[:option1] %>
    <p></p>
    <%= f.radio_button :response, "P" %>
    <%= f.label :option2, @answer[:option2] %>
    <p></p>
    <%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Personality Quiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar">
    <a class="navbar-brand" href="/personalities" ><h1>Personality Type Indicator</h1></a>
    <div>
        <% if logged_in? %>
          <button type="button" class="btn"><%= link_to 'Take the Quiz', quiz_question_1_path %></button>
          <button type="button" class="btn"><%= link_to 'Personality Types', personalities_path %></button>
          <button type="button" class="btn"><%= link_to 'User Profiles', users_path %></button>
          <button type="button" class="btn"><%= link_to 'Edit my Profile', edit_user_path(current_user.id) %></button>
          <button type="button" class="btn"><%= link_to 'Logout', logout_path %></button>
        <% end %>
      </div>
  </nav>
  <body class="text-dark">
    <p></p>
    <div class="container-fluid px-5" >
      <%= yield %>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/personalities/index.html.erb
<table class="table">
  <tbody>
    <tr>
      <td><%= link_to 'INTJ', personality_path(Personality.find_by(name: "INTJ")) %></td>
      <td><%= link_to 'INTP', personality_path(Personality.find_by(name: "INTP")) %></td>
      <td><%= link_to 'ENTJ', personality_path(Personality.find_by(name: "ENTJ")) %></td>
      <td><%= link_to 'ENTP', personality_path(Personality.find_by(name: "ENTP")) %></td>
    </tr>
    <tr>
      <td><%= link_to 'INFJ', personality_path(Personality.find_by(name: "INFJ")) %></td>
      <td><%= link_to 'INFP', personality_path(Personality.find_by(name: "INFP")) %></td>
      <td><%= link_to 'ENFJ', personality_path(Personality.find_by(name: "ENFJ")) %></td>
      <td><%= link_to 'ENFP', personality_path(Personality.find_by(name: "ENFP")) %></td>
    </tr>
    <tr>
      <td><%= link_to 'ISTJ', personality_path(Personality.find_by(name: "ISTJ")) %></td>
      <td><%= link_to 'ISFJ', personality_path(Personality.find_by(name: "ISFJ")) %></td>
      <td><%= link_to 'ESTJ', personality_path(Personality.find_by(name: "ESTJ")) %></td>
      <td><%= link_to 'ESFJ', personality_path(Personality.find_by(name: "ENTP")) %></td>
    </tr>
    <tr>
      <td><%= link_to 'ISTP', personality_path(Personality.find_by(name: "ISTP")) %></td>
      <td><%= link_to 'ISFP', personality_path(Personality.find_by(name: "ISFP")) %></td>
      <td><%= link_to 'ESTP', personality_path(Personality.find_by(name: "ESTP")) %></td>
      <td><%= link_to 'ESFP', personality_path(Personality.find_by(name: "ESFP")) %></td>
    </tr>
  </tbody>
</table>

app/views/personalities/show.html.erb
<div class="container my-5">
<h1><%= @personality.name %> - <%= @personality.nickname %></h1>
<h3><%= @personality.brief %></h3>
<p><%= @personality.description %></p>
</div>

app/views/users/edit.html.erb
<h1>Edit my Profile</h1>

<div class="form-group">
<%= form_for @user do |f| %>
    <%= f.label "Username: " %>
    <div class="colo-sm-10">
        <%= f.text_field :username %><br>
    </div>
    <p></p>
    <%= f.label "Name: " %>
    <div class="colo-sm-10">
        <%= f.text_field :name %><br>
    </div>
    <p></p>
    <%= f.label "Bio: " %>
    <div class="colo-sm-10">
        <%= f.text_area :bio %><br>
    </div>
    <p></p>
    <%= f.submit "Update My Profile" %>
<% end %>
<p></p>
<div>
<%= link_to "Delete this profile", user_path(@user), method: :delete %>
</div>
    
    

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
    <%= link_to user.name, user_path(user) %>
    <p></p>
<% end %>

app/views/users/new.html.erb
<h1>Create a New User</h1>
<%= form_for @user do |f| %>
    <p></p>
    <%= f.label :username %><br>
    <%= f.text_field :username %><br>
    <p></p>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <p></p>
    <%= f.label :bio %><br>
    <%= f.text_area :bio %><br>
    <p></p>
    <%= f.label "Friends: " %>
    <%= f.collection_check_boxes(:friend_ids , User.all, :id, :name ) do |b| %><br>
        <%= b.label(class: "label-checkbox") { b.check_box + "  " + b.text } %>
    <% end %>
    <p></p>
    <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<h6>(<%= @user.username %>)</h6>
<h3>Personality Type:
<% if !AnswersUser.find_by(user_id: @user.id) %>
    <%= "TBD" %>
<% else %>
    <% my_personality = @user.calculate_personality %>
    <%= link_to @user.personality.name, personality_path(my_personality.id) %>
<% end %>
</h3>
<p><%= @user.bio %></p>

<h5>
<% if @user.friends.count > 0 %>
    <%= "Friends:" %><br>
    <% @user.friends.each do |friend| %> 
        <% fri = User.find(friend.friend_id.to_i) %>
        <%= link_to fri.name, user_path(fri) %><br>
    <% end %>
<% end %>
</h5>